### PR TITLE
Added a possible approach to opening up the UIs in the exporter to a …

### PR DESCRIPTION
**Pull request by dashielb1010**
…hook.

Modifications are marked either 'UI Hook' or 'CBSD Customizations' in
comments. These represent different features brought by this commit. The
modifications marked 'CBSD Customization' rely on the presence of the 'UI
Hook', but I'd like to note that the 'UI Hook' modifications seem
generally more useful whereas the 'CBSD...' modifications more specific
to our studio. I am intending for the changes marked 'UI Hook' to be
considered separately. This is my attempt at addressing the two
request/suggestions from the Shotgun Support Request #85185 I opened.

Enjoy at your convenience!

### CODE REVIEW

**Comment by dashielb1010** [comment]
Well this embarrasing! After testing this I believe that the GUI properties are not begin transferred to the Processor/Updater at runtime. The GUI elements are obviously appearing but they're not connected somehow! I had this working but did some rearranging to try to maximize the control provided by the hook and didn't test it properly afterward. I'll have to see what the issue is and I'll post an update commit ASAP.

**Comment by thebeeland** [comment]
Hey Dashiel, thanks for the PR! We're digging into this now and will keep you posted.

**Comment by thebeeland** [comment]
Hey @dashielb1010 -- I saw that you already chimed in on my PR, so this won't come as a surprise, but our implementation of what you've done here will go out as tk-hiero-export v0.5.0 very soon. QA is giving the app store bundle one last look before I pull the trigger on the release.

Please give it a shot, and if you have any problems with it feel free to get in touch!

Thanks a ton for the hard work. This is a really, really great addition to the app and we're grateful you were willing to share it with us!

**Comment by dashielb1010** [comment]
Hey Jeff!

Cheers, and thank *you all* for the hard work. I can't wait to bring up the
new version, and am very pleased that my suggestions were well received!

I'm neck deep trying to get a Nuke pipeline working but I'll circle back to
this once I have a chance.


Thanks bunches!
-Dashiel

**Pull request closed without merging**
